name: Build App
on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', '1.21.x','1.22.x' ]

    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
           go-version: ${{ matrix.go-version }}
        - run: go install .
        - run: go build -v ./...    
